### ISSUE TITLE
权限该如何控制呢？

### ISSUE THREAD

**Issue by hanbing** [2388386839/syj-minicode#3]
使用时有几问题？
1、接口调用的权限该如何控制呢？
2、直接暴露表名是否合适呢？
3、涉及大于小于查询时该如何传条件？
4、如果要多表联合查询，可以自定义sql吗？

**Comment by shiyujun** [comment]
> 
> 
> 使用时有几问题？
> 1、接口调用的权限该如何控制呢？
> 2、直接暴露表名是否合适呢？
> 3、涉及大于小于查询时该如何传条件？
> 4、如果要多表联合查询，可以自定义sql吗？


    接口权限建议使用拦截器拦截entityName然后根据访问的url进行鉴权
    支持使用实体名称（符合驼峰命名）
    大于小于以及不等于的查询条件已经增加，请使用版本0.0.2
    4.新增了一个可以执行自定义sql的接口，但是不建议暴露出去，可以在service适当使用
