### ISSUE TITLE
访问报错

### ISSUE THREAD

**Issue by JavaZhangYin** [2388386839/syj-minicode#4]
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseMapper' available

**Comment by JavaZhangYin** [comment]
我访问的路径是：http://localhost/syj-api/User/3
用springboot配置
`@SpringBootApplication
@EnableSyjMiniCode
public class SpringbootPagehelperDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringbootPagehelperDemoApplication.class, args);
    }
}
`

**Comment by shiyujun** [comment]
> 
> 
> 我访问的路径是：http://localhost/syj-api/User/3
> 用springboot配置
> `@SpringBootApplication
> @EnableSyjMiniCode
> public class SpringbootPagehelperDemoApplication {
> 
> ```
> public static void main(String[] args) {
>     SpringApplication.run(SpringbootPagehelperDemoApplication.class, args);
> }
> ```
> 
> }
> `

请使用0.0.3及以上版本即可解决此问题

**Comment by JavaZhangYin** [comment]
> > 我访问的路径是：http://localhost/syj-api/User/3
> > 用springboot配置
> > `@SpringBootApplication
> > @EnableSyjMiniCode
> > public class SpringbootPagehelperDemoApplication {
> > ```
> > public static void main(String[] args) {
> >     SpringApplication.run(SpringbootPagehelperDemoApplication.class, args);
> > }
> > ```
> > }
> > `
> 
> 请使用0.0.3及以上版本即可解决此问题

还有一个错误是建立一张表名字叫做user就会出问题 他会查询mysql系统的user表

**Comment by JavaZhangYin** [comment]
如果有外键的话查询会报错 他会把外键也当作一个字段，但是我的entity里没有这个属性

**Comment by shiyujun** [comment]
> 如果有外键的话查询会报错 他会把外键也当作一个字段，但是我的entity里没有这个属性

请使用0.0.4版本，具体细节可以参考扩展2.3
